# Total de actores/actrices candidatos al Óscar que tienen las películas más famosas por género.

## Y al final contestar dos preguntas:

* ¿Cuál es el género con mayor número de candidaturas?

* ¿Cuál es la película con mayor diferencia porcentual de candidaturas respecto a la media de su género?

In [1]:
import re
import json
from urllib.parse import urljoin
import requests
from bs4 import BeautifulSoup
import pandas as pd

## Extraer las 30 mejores películas de los geneos de acción, comédia, drama y terror en FilmAffinity, además películas del año 1980 en adelante.

In [2]:
full_peliculas = []  # Lista vacía para almacenar la información de las películas
generos = {'acción', 'comedia', 'drama', 'terror'}  # Conjunto de géneros

# Iterar sobre cada género
for genero in generos:
    # Construir la URL para cada género
    genre_url = f'https://www.filmaffinity.com/es/topgen.php?genres=%2B{genero[:2].upper()}&chv=0&orderby=rc&movietype=movie%7C&country=&fromyear=1980&toyear=2023&ratingcount=2&runtimemin=0&runtimemax=4'
    
    # Realizar una solicitud GET a la URL del género y obtener la página
    req = requests.get(genre_url)
    
    # Crear un objeto BeautifulSoup para analizar el HTML de la página del género
    soup = BeautifulSoup(req.text, 'html.parser')
    
    # Encontrar todas las películas en la página del género utilizando la clase 'mc-title'
    for pelicula in soup.select('.mc-title'):
        # Obtener el título de la película
        titulo = pelicula.text.strip()
        
        # Encontrar el div siguiente que contiene el reparto utilizando la clase 'mc-cast'
        cast_div = pelicula.find_next_sibling(class_='mc-cast')
        
        # Obtener los nombres de los actores de los elementos '.nb' dentro del div de reparto
        actores = [actor.text.strip() for actor in cast_div.select('.nb') if actor.a]
        
        # Agregar la información de la película a la lista de películas
        full_peliculas.append({
            "title": titulo.split("(")[0].strip(),  # Título de la película
            "year": titulo.split("(")[1].strip().replace(")", ""),  # Año de la película
            "genre": genero,  # Género de la película
            "actors": ", ".join(actores)  # Lista de actores de la película
        })    

# Devolver la lista completa de películas recolectadas
full_peliculas

[{'title': 'Forrest Gump',
  'year': '1994',
  'genre': 'comedia',
  'actors': 'Tom Hanks,, Robin Wright,, Gary Sinise,, Mykelti Williamson,, Sally Field,, Rebecca Williams,, Michael Conner Humphreys,, Haley Joel Osment'},
 {'title': 'La vida es bella',
  'year': '1997',
  'genre': 'comedia',
  'actors': 'Roberto Benigni,, Nicoletta Braschi,, Giorgio Cantarini,, Marisa Paredes,, Giustino Durano,, Horst Buchholz,, Sergio Bini Bustric'},
 {'title': 'American Beauty',
  'year': '1999',
  'genre': 'comedia',
  'actors': 'Kevin Spacey,, Annette Bening,, Thora Birch,, Allison Janney,, Peter Gallagher,, Mena Suvari,, Wes Bentley,, Chris Cooper'},
 {'title': 'El rey león',
  'year': '1994',
  'genre': 'comedia',
  'actors': 'Matthew Broderick,, Jeremy Irons,, Jonathan Taylor Thomas,, Moira Kelly,, Rowan Atkinson,, Whoopi Goldberg,, Cheech Marin'},
 {'title': 'Toy Story',
  'year': '1995',
  'genre': 'comedia',
  'actors': 'Tom Hanks,, Tim Allen,, Don Rickles,, Jim Varney,, Wallace Shawn,, John Ratzenberger,, Annie Potts,, R. Lee Ermey'},
 {'title': 'Amélie',
  'year': '2001',
  'genre': 'comedia',
  'actors': 'Audrey Tautou,, Mathieu Kassovitz,, Rufus Magloire,, Lorella Cravotta,, Serge Merlin,, Jamel Debbouze,, Claire Maurier,, Clotilde Mollet'},
 {'title': 'Malditos bastardos',
  'year': '2009',
  'genre': 'comedia',
  'actors': 'Brad Pitt,, Christoph Waltz,, Mélanie Laurent,, Diane Kruger,, Michael Fassbender,, Daniel Brühl,, Eli Roth,, Til Schweiger'},
 {'title': 'Shrek',
  'year': '2001',
  'genre': 'comedia',
  'actors': 'Mike Myers,, Eddie Murphy,, Cameron Diaz,, John Lithgow'},
 {'title': 'Algo pasa con Mary',
  'year': '1998',
  'genre': 'comedia',
  'actors': 'Cameron Diaz,, Ben Stiller,, Matt Dillon,, Chris Elliott,, Lee Evans,, Lin Shaye,, W. Earl Brown,, Keith David'},
 {'title': 'Piratas del Caribe: La maldición de la Perla Negra',
  'year': '2003',
  'genre': 'comedia',
  'actors': 'Johnny Depp,, Orlando Bloom,, Keira Knightley,, Geoffrey Rush,, Jack Davenport,, Kevin McNally,, Jonathan Pryce,, Mackenzie Crook'},
 {'title': 'Monstruos, S.A.',
  'year': '2001',
  'genre': 'comedia',
  'actors': 'John Goodman,, Billy Crystal,, Mary Gibbs,, Steve Buscemi,, James Coburn,, Jennifer Tilly,, Bob Peterson'},
 {'title': 'Up',
  'year': '2009',
  'genre': 'comedia',
  'actors': 'Ed Asner,, Christopher Plummer,, Jordan Nagai,, Bob Peterson,, Delroy Lindo,, Jerome Ranft,, John Ratzenberger'},
 {'title': 'Buscando a Nemo',
  'year': '2003',
  'genre': 'comedia',
  'actors': 'Albert Brooks,, Ellen DeGeneres,, Alexander Gould,, Willem Dafoe,, Brad Garrett,, Allison Janney,, Austin Pendleton'},
 {'title': 'Regreso al futuro',
  'year': '1985',
  'genre': 'comedia',
  'actors': 'Michael J. Fox,, Christopher Lloyd,, Lea Thompson,, Crispin Glover,, Claudia Wells,, Thomas F. Wilson,, James Tolkan,, Billy Zane'},
 {'title': 'Men in Black',
  'year': 'Hombres de negro',
  'genre': 'comedia',
  'actors': "Tommy Lee Jones,, Will Smith,, Linda Fiorentino,, Vincent D'Onofrio,, Rip Torn,, Tony Shalhoub,, Siobhan Fallon,, Mike Nussbaum"},
 {'title': 'Snatch. Cerdos y diamantes',
  'year': '2000',
  'genre': 'comedia',
  'actors': 'Jason Statham,, Stephen Graham,, Brad Pitt,, Alan Ford,, Vinnie Jones,, Rade Serbedzija,, Dennis Farina,, Benicio del Toro'},
 {'title': 'Mejor... imposible',
  'year': '1997',
  'genre': 'comedia',
  'actors': 'Jack Nicholson,, Helen Hunt,, Greg Kinnear,, Cuba Gooding Jr.,, Skeet Ulrich,, Shirley Knight,, Jesse James,, Lawrence Kasdan'},
 {'title': 'Shrek 2',
  'year': '2004',
  'genre': 'comedia',
  'actors': 'Mike Myers,, Eddie Murphy,, Cameron Diaz,, Antonio Banderas,, Jennifer Saunders,, Rupert Everett,, Julie Andrews,, John Cleese'},
 {'title': 'Pretty Woman',
  'year': '1990',
  'genre': 'comedia',
  'actors': 'Julia Roberts,, Richard Gere,, Hector Elizondo,, Jason Alexander,, Ralph Bellamy,, Laura San Giacomo,, Hank Azaria,, Larry Miller'},
 {'title': 'Dos tontos muy tontos',
  'year': '1994',
  'genre': 'comedia',
  'actors': 'Jim Carrey,, Jeff Daniels,, Lauren Holly,, Mike Starr,, Charles Rocket,, Victoria Rowell,, Joe Baker,, Hank Brandt'},
 {'title': 'El show de Truman',
  'year': '1998',
  'genre': 'comedia',
  'actors': 'Jim Carrey,, Laura Linney,, Noah Emmerich,, Ed Harris,, Natascha McElhone,, Holland Taylor,, Paul Giamatti,, Adam Tomei'},
 {'title': 'La edad de hielo',
  'year': 'Ice Age',
  'genre': 'comedia',
  'actors': 'Ray Romano,, John Leguizamo,, Denis Leary,, Jack Black,, Alan Tudyk,, Chris Wedge'},
 {'title': 'El gran Lebowski',
  'year': '1998',
  'genre': 'comedia',
  'actors': 'Jeff Bridges,, John Goodman,, Julianne Moore,, Steve Buscemi,, David Huddleston,, Philip Seymour Hoffman,, Sam Elliott,, John Turturro'},
 {'title': 'Solo en casa',
  'year': '1990',
  'genre': 'comedia',
  'actors': "Macaulay Culkin,, Joe Pesci,, Daniel Stern,, John Heard,, Roberts Blossom,, Catherine O'Hara,, John Candy,, Angela Goethals"},
 {'title': 'Los cazafantasmas',
  'year': '1984',
  'genre': 'comedia',
  'actors': 'Bill Murray,, Dan Aykroyd,, Sigourney Weaver,, Harold Ramis,, Ernie Hudson,, Rick Moranis,, William Atherton,, Annie Potts'},
 {'title': 'Toy Story 3',
  'year': '2010',
  'genre': 'comedia',
  'actors': 'Tom Hanks,, Tim Allen,, Joan Cusack,, Don Rickles,, Estelle Harris,, Blake Clark,, Wallace Shawn'},
 {'title': 'Toy Story 2',
  'year': '1999',
  'genre': 'comedia',
  'actors': 'Tom Hanks,, Tim Allen,, Joan Cusack,, Don Rickles,, Estelle Harris,, Kelsey Grammer,, Jim Varney'},
 {'title': 'American Pie',
  'year': '1999',
  'genre': 'comedia',
  'actors': 'Jason Biggs,, Chris Klein,, Thomas Ian Nicholas,, Alyson Hannigan,, Shannon Elizabeth,, Tara Reid,, Eddie Kaye Thomas,, Seann William Scott'},
 {'title': 'Intocable',
  'year': '2011',
  'genre': 'comedia',
  'actors': 'François Cluzet,, Omar Sy,, Anne Le Ny,, Audrey Fleurot,, Clotilde Mollet,, Joséphine de Meaux,, Alba Gaïa Bellugi,, Cyril Mendy'},
 {'title': 'Scary Movie',
  'year': '2000',
  'genre': 'comedia',
  'actors': 'Anna Faris,, Jon Abrahams,, Carmen Electra,, Shannon Elizabeth,, Kurt Fuller,, Regina Hall,, Lochlyn Munro,, Cheri Oteri'},
 {'title': 'Matrix',
  'year': '1999',
  'genre': 'acción',
  'actors': 'Keanu Reeves,, Laurence Fishburne,, Carrie-Anne Moss,, Joe Pantoliano,, Hugo Weaving,, Marcus Chong,, Gloria Foster,, Matt Doran'},
 {'title': 'El señor de los anillos: La comunidad del anillo',
  'year': '2001',
  'genre': 'acción',
  'actors': 'Elijah Wood,, Ian McKellen,, Viggo Mortensen,, Sean Astin,, Sean Bean,, John Rhys-Davies,, Orlando Bloom,, Dominic Monaghan'},
 {'title': 'Gladiator',
  'year': '2000',
  'genre': 'acción',
  'actors': 'Russell Crowe,, Joaquin Phoenix,, Connie Nielsen,, Oliver Reed,, Richard Harris,, Ralf Moeller,, Derek Jacobi,, Djimon Hounsou'},
 {'title': 'Kill Bill. Volumen 1',
  'year': '2003',
  'genre': 'acción',
  'actors': 'Uma Thurman,, Lucy Liu,, Daryl Hannah,, Vivica A. Fox,, Sonny Chiba,, Chiaki Kuriyama,, Michael Bowen,, Julie Dreyfus'},
 {'title': 'El señor de los anillos: El retorno del rey',
  'year': '2003',
  'genre': 'acción',
  'actors': 'Elijah Wood,, Viggo Mortensen,, Ian McKellen,, Sean Astin,, Andy Serkis,, John Rhys-Davies,, Orlando Bloom,, John Noble'},
 {'title': 'El señor de los anillos: Las dos torres',
  'year': '2002',
  'genre': 'acción',
  'actors': 'Elijah Wood,, Viggo Mortensen,, Ian McKellen,, Sean Astin,, Andy Serkis,, John Rhys-Davies,, Orlando Bloom,, Bernard Hill'},
 {'title': 'Avatar',
  'year': '2009',
  'genre': 'acción',
  'actors': 'Sam Worthington,, Zoe Saldana,, Sigourney Weaver,, Stephen Lang,, Michelle Rodriguez,, Giovanni Ribisi,, Joel David Moore,, Wes Studi'},
 {'title': 'Origen',
  'year': '2010',
  'genre': 'acción',
  'actors': 'Leonardo DiCaprio,, Joseph Gordon-Levitt,, Elliot Page,, Ken Watanabe,, Marion Cotillard,, Tom Hardy,, Cillian Murphy,, Tom Berenger'},
 {'title': 'Malditos bastardos',
  'year': '2009',
  'genre': 'acción',
  'actors': 'Brad Pitt,, Christoph Waltz,, Mélanie Laurent,, Diane Kruger,, Michael Fassbender,, Daniel Brühl,, Eli Roth,, Til Schweiger'},
 {'title': 'Piratas del Caribe: La maldición de la Perla Negra',
  'year': '2003',
  'genre': 'acción',
  'actors': 'Johnny Depp,, Orlando Bloom,, Keira Knightley,, Geoffrey Rush,, Jack Davenport,, Kevin McNally,, Jonathan Pryce,, Mackenzie Crook'},
 {'title': 'El caballero oscuro',
  'year': '2008',
  'genre': 'acción',
  'actors': 'Christian Bale,, Heath Ledger,, Aaron Eckhart,, Michael Caine,, Gary Oldman,, Morgan Freeman,, Maggie Gyllenhaal,, Eric Roberts'},
 {'title': '300',
  'year': '2006',
  'genre': 'acción',
  'actors': 'Gerard Butler,, Lena Headey,, David Wenham,, Dominic West,, Vincent Regan,, Tom Wisdom,, Rodrigo Santoro,, Andrew Tieman'},
 {'title': 'Terminator',
  'year': '1984',
  'genre': 'acción',
  'actors': 'Arnold Schwarzenegger,, Linda Hamilton,, Michael Biehn,, Paul Winfield,, Lance Henriksen,, Rick Rossovich,, Bess Motta,, Earl Boen'},
 {'title': 'Kill Bill. Volumen 2',
  'year': '2004',
  'genre': 'acción',
  'actors': 'Uma Thurman,, David Carradine,, Lucy Liu,, Vivica A. Fox,, Gordon Liu,, Michael Madsen,, Daryl Hannah,, Michael Parks'},
 {'title': 'Men in Black',
  'year': 'Hombres de negro',
  'genre': 'acción',
  'actors': "Tommy Lee Jones,, Will Smith,, Linda Fiorentino,, Vincent D'Onofrio,, Rip Torn,, Tony Shalhoub,, Siobhan Fallon,, Mike Nussbaum"},
 {'title': 'Reservoir Dogs',
  'year': '1992',
  'genre': 'acción',
  'actors': 'Tim Roth,, Harvey Keitel,, Steve Buscemi,, Michael Madsen,, Chris Penn,, Lawrence Tierney,, Randy Brooks,, Kirk Baltz'},
 {'title': 'Infiltrados',
  'year': '2006',
  'genre': 'acción',
  'actors': 'Leonardo DiCaprio,, Matt Damon,, Jack Nicholson,, Mark Wahlberg,, Vera Farmiga,, Alec Baldwin,, Martin Sheen,, Ray Winstone'},
 {'title': 'Blade Runner',
  'year': '1982',
  'genre': 'acción',
  'actors': 'Harrison Ford,, Rutger Hauer,, Sean Young,, Daryl Hannah,, Edward James Olmos,, Joanna Cassidy,, Brion James,, Joe Turkel'},
 {'title': 'En busca del arca perdida',
  'year': '1981',
  'genre': 'acción',
  'actors': 'Harrison Ford,, Karen Allen,, Paul Freeman,, Ronald Lacey,, John Rhys-Davies,, Vic Tablian,, Denholm Elliott,, Wolf Kahler'},
 {'title': 'V de Vendetta',
  'year': '2005',
  'genre': 'acción',
  'actors': 'Natalie Portman,, Hugo Weaving,, Stephen Rea,, John Hurt,, Rupert Graves,, Stephen Fry,, Tim Pigott-Smith,, Roger Allam'},
 {'title': 'Terminator 2: El juicio final',
  'year': '1991',
  'genre': 'acción',
  'actors': 'Arnold Schwarzenegger,, Linda Hamilton,, Edward Furlong,, Robert Patrick,, Earl Boen,, Joe Morton,, S. Epatha Merkerson,, Danny Cooksey'},
 {'title': 'Sin City',
  'year': 'Ciudad del pecado',
  'genre': 'acción',
  'actors': 'Bruce Willis,, Mickey Rourke,, Clive Owen,, Rosario Dawson,, Jessica Alba,, Benicio del Toro,, Elijah Wood,, Marley Shelton'},
 {'title': 'Indiana Jones y la última cruzada',
  'year': '1989',
  'genre': 'acción',
  'actors': 'Harrison Ford,, Sean Connery,, Alison Doody,, Denholm Elliott,, John Rhys-Davies,, River Phoenix,, Julian Glover,, Michael Byrne'},
 {'title': 'Jungla de cristal',
  'year': '1988',
  'genre': 'acción',
  'actors': 'Bruce Willis,, Bonnie Bedelia,, Alan Rickman,, Alexander Godunov,, Paul Gleason,, Reginald Veljohnson,, William Atherton,, Hart Bochner'},
 {'title': 'Matrix Revolutions',
  'year': '2003',
  'genre': 'acción',
  'actors': 'Keanu Reeves,, Laurence Fishburne,, Carrie-Anne Moss,, Hugo Weaving,, Jada Pinkett Smith,, Harold Perrineau,, Nona Gaye,, Clayton Watson'},
 {'title': 'X-Men',
  'year': '2000',
  'genre': 'acción',
  'actors': 'Hugh Jackman,, Patrick Stewart,, Ian McKellen,, Anna Paquin,, Halle Berry,, Famke Janssen,, Bruce Davison,, James Marsden'},
 {'title': 'Indiana Jones y el templo maldito',
  'year': '1984',
  'genre': 'acción',
  'actors': 'Harrison Ford,, Kate Capshaw,, Ke Huy Quan,, Amrish Puri,, Roshan Seth,, Roy Chiao,, Philip Stone,, Raj Singh'},
 {'title': 'Batman',
  'year': '1989',
  'genre': 'acción',
  'actors': 'Michael Keaton,, Jack Nicholson,, Kim Basinger,, Robert Wuhl,, Pat Hingle,, Billy Dee Williams,, Michael Gough,, Jack Palance'},
 {'title': 'Batman Begins',
  'year': '2005',
  'genre': 'acción',
  'actors': 'Christian Bale,, Liam Neeson,, Katie Holmes,, Cillian Murphy,, Michael Caine,, Morgan Freeman,, Gary Oldman,, Ken Watanabe'},
 {'title': 'El caso Bourne',
  'year': '2002',
  'genre': 'acción',
  'actors': 'Matt Damon,, Franka Potente,, Chris Cooper,, Brian Cox,, Clive Owen,, Adewale Akinnuoye-Agbaje,, Gabriel Mann,, Julia Stiles'},
 {'title': 'Forrest Gump',
  'year': '1994',
  'genre': 'drama',
  'actors': 'Tom Hanks,, Robin Wright,, Gary Sinise,, Mykelti Williamson,, Sally Field,, Rebecca Williams,, Michael Conner Humphreys,, Haley Joel Osment'},
 {'title': 'La vida es bella',
  'year': '1997',
  'genre': 'drama',
  'actors': 'Roberto Benigni,, Nicoletta Braschi,, Giorgio Cantarini,, Marisa Paredes,, Giustino Durano,, Horst Buchholz,, Sergio Bini Bustric'},
 {'title': 'El club de la lucha',
  'year': '1999',
  'genre': 'drama',
  'actors': 'Edward Norton,, Brad Pitt,, Helena Bonham Carter,, Meat Loaf,, Jared Leto,, Van Quattro,, Markus Redmond,, Michael Girardin'},
 {'title': 'Gladiator',
  'year': '2000',
  'genre': 'drama',
  'actors': 'Russell Crowe,, Joaquin Phoenix,, Connie Nielsen,, Oliver Reed,, Richard Harris,, Ralf Moeller,, Derek Jacobi,, Djimon Hounsou'},
 {'title': 'Titanic',
  'year': '1997',
  'genre': 'drama',
  'actors': 'Leonardo DiCaprio,, Kate Winslet,, Billy Zane,, Kathy Bates,, Frances Fisher,, Gloria Stuart,, Bill Paxton,, Bernard Hill'},
 {'title': 'La lista de Schindler',
  'year': '1993',
  'genre': 'drama',
  'actors': 'Liam Neeson,, Ben Kingsley,, Ralph Fiennes,, Caroline Goodall,, Jonathan Sagall,, Embeth Davidtz,, Norbert Weisser,, Martin S. Bergmann'},
 {'title': 'American Beauty',
  'year': '1999',
  'genre': 'drama',
  'actors': 'Kevin Spacey,, Annette Bening,, Thora Birch,, Allison Janney,, Peter Gallagher,, Mena Suvari,, Wes Bentley,, Chris Cooper'},
 {'title': 'Cadena perpetua',
  'year': '1994',
  'genre': 'drama',
  'actors': 'Tim Robbins,, Morgan Freeman,, Bob Gunton,, James Whitmore,, Gil Bellows,, William Sadler,, Mark Rolston,, Clancy Brown'},
 {'title': 'Million Dollar Baby',
  'year': '2004',
  'genre': 'drama',
  'actors': "Clint Eastwood,, Hilary Swank,, Morgan Freeman,, Anthony Mackie,, Jay Baruchel,, Mike Colter,, Lucia Rijker,, Brian F. O'Byrne"},
 {'title': 'El sexto sentido',
  'year': '1999',
  'genre': 'drama',
  'actors': 'Haley Joel Osment,, Bruce Willis,, Toni Collette,, Olivia Williams,, Trevor Morgan,, Donnie Wahlberg,, Peter Tambakis,, Jeffrey Zubernis'},
 {'title': 'El rey león',
  'year': '1994',
  'genre': 'drama',
  'actors': 'Matthew Broderick,, Jeremy Irons,, Jonathan Taylor Thomas,, Moira Kelly,, Rowan Atkinson,, Whoopi Goldberg,, Cheech Marin'},
 {'title': 'Amélie',
  'year': '2001',
  'genre': 'drama',
  'actors': 'Audrey Tautou,, Mathieu Kassovitz,, Rufus Magloire,, Lorella Cravotta,, Serge Merlin,, Jamel Debbouze,, Claire Maurier,, Clotilde Mollet'},
 {'title': 'E.T. el extraterrestre',
  'year': '1982',
  'genre': 'drama',
  'actors': 'Henry Thomas,, Dee Wallace,, Robert MacNaughton,, Drew Barrymore,, Peter Coyote,, C. Thomas Howell,, K.C. Martel,, Sean Frye'},
 {'title': 'El caballero oscuro',
  'year': '2008',
  'genre': 'drama',
  'actors': 'Christian Bale,, Heath Ledger,, Aaron Eckhart,, Michael Caine,, Gary Oldman,, Morgan Freeman,, Maggie Gyllenhaal,, Eric Roberts'},
 {'title': 'Braveheart',
  'year': '1995',
  'genre': 'drama',
  'actors': "Mel Gibson,, Sophie Marceau,, Patrick McGoohan,, Angus MacFadyen,, Catherine McCormack,, Brendan Gleeson,, David O'Hara,, Tommy Flanagan"},
 {'title': 'El pianista',
  'year': '2002',
  'genre': 'drama',
  'actors': 'Adrien Brody,, Thomas Kretschmann,, Maureen Lipman,, Ed Stoppard,, Emilia Fox,, Frank Finlay,, Julia Rayner,, Jessica Kate Meyer., Morgane Polanski'},
 {'title': 'American History X',
  'year': '1998',
  'genre': 'drama',
  'actors': "Edward Norton,, Edward Furlong,, Fairuza Balk,, Stacy Keach,, Elliott Gould,, Avery Brooks,, Beverly D'Angelo,, Jennifer Lien"},
 {'title': 'Gran Torino',
  'year': '2008',
  'genre': 'drama',
  'actors': 'Clint Eastwood,, Christopher Carley,, Bee Vang,, Ahney Her,, John Carroll Lynch,, Cory Hardrict,, Brian Haley,, Geraldine Hughes'},
 {'title': 'Infiltrados',
  'year': '2006',
  'genre': 'drama',
  'actors': 'Leonardo DiCaprio,, Matt Damon,, Jack Nicholson,, Mark Wahlberg,, Vera Farmiga,, Alec Baldwin,, Martin Sheen,, Ray Winstone'},
 {'title': 'Trainspotting',
  'year': '1996',
  'genre': 'drama',
  'actors': 'Ewan McGregor,, Robert Carlyle,, Jonny Lee Miller,, Ewen Bremner,, Kelly MacDonald,, Kevin McKidd,, Peter Mullan,, James Cosmo'},
 {'title': 'Slumdog Millionaire',
  'year': '2008',
  'genre': 'drama',
  'actors': 'Dev Patel,, Freida Pinto,, Madhur Mittal,, Anil Kapoor,, Irrfan Khan,, Saurabh Shukla,, Mia Drake,, Rajendranath Zutshi'},
 {'title': 'Mystic River',
  'year': '2003',
  'genre': 'drama',
  'actors': 'Sean Penn,, Tim Robbins,, Kevin Bacon,, Laurence Fishburne,, Marcia Gay Harden,, Laura Linney,, Eli Wallach,, Tom Guiry'},
 {'title': 'Mejor... imposible',
  'year': '1997',
  'genre': 'drama',
  'actors': 'Jack Nicholson,, Helen Hunt,, Greg Kinnear,, Cuba Gooding Jr.,, Skeet Ulrich,, Shirley Knight,, Jesse James,, Lawrence Kasdan'},
 {'title': 'Big Fish',
  'year': '2003',
  'genre': 'drama',
  'actors': 'Ewan McGregor,, Albert Finney,, Billy Crudup,, Jessica Lange,, Alison Lohman,, Helena Bonham Carter,, Steve Buscemi,, Danny DeVito'},
 {'title': 'Moulin Rouge',
  'year': '2001',
  'genre': 'drama',
  'actors': 'Nicole Kidman,, Ewan McGregor,, John Leguizamo,, David Wenham,, Jim Broadbent,, Richard Roxburgh,, Jacek Koman,, Kylie Minogue'},
 {'title': 'Ciudad de Dios',
  'year': '2002',
  'genre': 'drama',
  'actors': 'Alexandre Rodrigues,, Leandro Firmino,, Phellipe Haagensen,, Douglas Silva,, Seu Jorge,, Jonathan Haagensen,, Matheus Nachtergaele,, Jefechander Suplino'},
 {'title': 'El show de Truman',
  'year': '1998',
  'genre': 'drama',
  'actors': 'Jim Carrey,, Laura Linney,, Noah Emmerich,, Ed Harris,, Natascha McElhone,, Holland Taylor,, Paul Giamatti,, Adam Tomei'},
 {'title': 'El curioso caso de Benjamin Button',
  'year': '2008',
  'genre': 'drama',
  'actors': 'Brad Pitt,, Cate Blanchett,, Taraji P. Henson,, Tilda Swinton,, Jason Flemyng,, Julia Ormond,, Elias Koteas,, Elle Fanning'},
 {'title': 'La chaqueta metálica',
  'year': '1987',
  'genre': 'drama',
  'actors': "Matthew Modine,, Vincent D'Onofrio,, R. Lee Ermey,, Adam Baldwin,, Arliss Howard,, Dorian Harewood,, Kevyn Major Howard,, Ed O'Ross"},
 {'title': 'Réquiem por un sueño',
  'year': '2000',
  'genre': 'drama',
  'actors': 'Jared Leto,, Jennifer Connelly,, Ellen Burstyn,, Marlon Wayans,, Christopher McDonald,, Louise Lasser,, Marcia Jean Kurtz,, Janet Sarno'},
 {'title': 'El sexto sentido',
  'year': '1999',
  'genre': 'terror',
  'actors': 'Haley Joel Osment,, Bruce Willis,, Toni Collette,, Olivia Williams,, Trevor Morgan,, Donnie Wahlberg,, Peter Tambakis,, Jeffrey Zubernis'},
 {'title': 'Los otros',
  'year': '2001',
  'genre': 'terror',
  'actors': 'Nicole Kidman,, Fionnula Flanagan,, Christopher Eccleston,, Alakina Mann,, James Bentley,, Eric Sykes,, Elaine Cassidy,, Renée Asherson,, Michelle Fairley'},
 {'title': 'El resplandor',
  'year': '1980',
  'genre': 'terror',
  'actors': 'Jack Nicholson,, Shelley Duvall,, Danny Lloyd,, Scatman Crothers,, Barry Nelson,, Philip Stone,, Joe Turkel,, Lia Beldam'},
 {'title': 'Scary Movie',
  'year': '2000',
  'genre': 'terror',
  'actors': 'Anna Faris,, Jon Abrahams,, Carmen Electra,, Shannon Elizabeth,, Kurt Fuller,, Regina Hall,, Lochlyn Munro,, Cheri Oteri'},
 {'title': 'Saw',
  'year': '2004',
  'genre': 'terror',

In [3]:
movies = pd.DataFrame(full_peliculas)
movies["name"] = movies["actors"].str.split(",")
movies

,title,year,genre,actors,name
0,Forrest Gump,1994,comedia,"Tom Hanks,, Robin Wright,, Gary Sinise,, Mykel...","[Tom Hanks, , Robin Wright, , Gary Sinise, ,..."
1,La vida es bella,1997,comedia,"Roberto Benigni,, Nicoletta Braschi,, Giorgio ...","[Roberto Benigni, , Nicoletta Braschi, , Gio..."
2,American Beauty,1999,comedia,"Kevin Spacey,, Annette Bening,, Thora Birch,, ...","[Kevin Spacey, , Annette Bening, , Thora Bir..."
3,El rey león,1994,comedia,"Matthew Broderick,, Jeremy Irons,, Jonathan Ta...","[Matthew Broderick, , Jeremy Irons, , Jonath..."
4,Toy Story,1995,comedia,"Tom Hanks,, Tim Allen,, Don Rickles,, Jim Varn...","[Tom Hanks, , Tim Allen, , Don Rickles, , J..."
...,...,...,...,...,...
115,American Psycho,2000,terror,"Christian Bale,, Willem Dafoe,, Jared Leto,, J...","[Christian Bale, , Willem Dafoe, , Jared Let..."
116,Abierto hasta el amanecer,1996,terror,"George Clooney,, Harvey Keitel,, Juliette Lewi...","[George Clooney, , Harvey Keitel, , Juliette..."
117,Destino final,2000,terror,"Devon Sawa,, Ali Larter,, Kerr Smith,, Seann W...","[Devon Sawa, , Ali Larter, , Kerr Smith, , ..."
118,Déjame entrar,2008,terror,"Kåre Hedebrant,, Lina Leandersson,, Per Ragnar...","[Kåre Hedebrant, , Lina Leandersson, , Per R..."
119,Death Proof,2007,terror,"Kurt Russell,, Rosario Dawson,, Vanessa Ferlit...","[Kurt Russell, , Rosario Dawson, , Vanessa F..."

In [4]:
movies = movies.explode("name").drop(columns="actors")
movies["name"] = movies["name"].str.strip()

In [5]:
movies = movies.reset_index(drop=True)

In [6]:
movies

             title  year    genre                     name
0     Forrest Gump  1994  comedia                Tom Hanks
1     Forrest Gump  1994  comedia
2     Forrest Gump  1994  comedia             Robin Wright
3     Forrest Gump  1994  comedia
4     Forrest Gump  1994  comedia              Gary Sinise
...            ...   ...      ...                      ...
1742   Death Proof  2007   terror             Rose McGowan
1743   Death Proof  2007   terror
1744   Death Proof  2007   terror             Tracie Thoms
1745   Death Proof  2007   terror
1746   Death Proof  2007   terror  Mary Elizabeth Winstead

[1747 rows x 4 columns]

## Extraer los galárdones del óscar a partir del año de 1980.

In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

actor_types = [
    ('al', 'actor'),
    ('a_la', 'actriz'),
    ('al', 'actor_de_reparto'),
    ('a_la', 'actriz_de_reparto')
]

all_actors_movies = []

for art, actor_type in actor_types:
    url = f'https://es.wikipedia.org/wiki/Anexo:%C3%93scar_{art}_mejor_{actor_type}'

    # Realizar la solicitud GET a la página
    response = requests.get(url)

    # Crear el objeto BeautifulSoup para analizar el HTML
    soup = BeautifulSoup(response.content, 'html.parser')

    # Encontrar todas las tablas en la página
    tablas = soup.find_all('table')

    # Lista para almacenar los actores y películas de esta URL
    actors_movies = []

    # Iterar sobre cada tabla y extraer los nombres de los actores y películas
    for tabla in tablas:
        filas = tabla.find_all('tr')  # Encontrar todas las filas de la tabla
        for fila in filas:
            columnas = fila.find_all(['th', 'td'])  # Encontrar las columnas (celdas de encabezado y datos)
            datos_fila = [columna.text.strip() for columna in columnas]  # Extraer texto de cada celda
            # Añadir a la lista si hay datos en la fila y no es un encabezado
            if datos_fila and len(datos_fila) >= 4 and datos_fila[0].isdigit():
                actor_pelicula = {
                    'actor': datos_fila[2],
                    'pelicula': datos_fila[3]
                }
                actors_movies.append(actor_pelicula)

    # Añadir los actores y películas extraídos de esta URL a la lista principal
    all_actors_movies.append({
        'actor_type': actor_type,
        'actors_movies': actors_movies
    })

# Crear un DataFrame con los datos recolectados
data = []
for table_info in all_actors_movies:
    for actor_pelicula in table_info['actors_movies']:
        data.append([actor_pelicula['actor'], actor_pelicula['pelicula']])

oscars = pd.DataFrame(data, columns=['name', 'Película'])

oscars

                 name                   Película
0      Brendan Fraser                  The Whale
1          Will Smith               King Richard
2     Anthony Hopkins                 The Father
3     Joaquin Phoenix                      Joker
4          Rami Malek          Bohemian Rhapsody
..                ...                        ...
438      Jane Darwell        The Grapes of Wrath
439   Hattie McDaniel  Lo que el viento se llevó
440       Fay Bainter                    Jezabel
441       Alice Brady             In Old Chicago
442  Gale Sondergaard            Anthony Adverse

[443 rows x 2 columns]

In [8]:
oscars = oscars.groupby("name").size().sort_values()
oscars = oscars.reset_index()
oscars.columns = ["name", "nominations"]
oscars

                           name  nominations
0                  Adrien Brody            1
1             Marcia Gay Harden            1
2    Lupita Nyong'o[1]​[2]​[3]​            1
3               Louise Fletcher            1
4            Louis Gossett, Jr.            1
..                          ...          ...
308           Frances McDormand            3
309            Daniel Day-Lewis            3
310              Ingrid Bergman            3
311           Katharine Hepburn            4
312                       Mujer           79

[313 rows x 2 columns]

In [9]:
df = movies.merge(oscars, on="name", how='inner')
df

                         title  year    genre             name  nominations
0                 Forrest Gump  1994  comedia        Tom Hanks            2
1                    Toy Story  1995  comedia        Tom Hanks            2
2                  Toy Story 3  2010  comedia        Tom Hanks            2
3                  Toy Story 2  1999  comedia        Tom Hanks            2
4                 Forrest Gump  1994    drama        Tom Hanks            2
..                         ...   ...      ...              ...          ...
111       Réquiem por un sueño  2000    drama    Ellen Burstyn            1
112                Soy leyenda  2007   terror    Emma Thompson            1
113     Drácula de Bram Stoker  1992   terror  Anthony Hopkins            2
114   Bienvenidos a Zombieland  2009   terror       Emma Stone            1
115  Abierto hasta el amanecer  1996   terror   George Clooney            1

[116 rows x 5 columns]

In [10]:
df.to_json("movies_actors.json")

## Género con más nominaciones:

In [11]:
df = pd.read_json("movies_actors.json")

In [12]:
df.groupby("genre")["nominations"].sum().sort_values(ascending=False)

genre
drama      55
comedia    39
acción     37
terror     16
Name: nominations, dtype: int64

## El género con más nominaciones es el drama.

In [13]:
df = df.groupby(["title", "genre"])["nominations"].sum()

In [14]:
df = df.reset_index()
df

                        title    genre  nominations
0   Abierto hasta el amanecer   terror            1
1             American Beauty  comedia            4
2             American Beauty    drama            4
3             American Psycho   terror            2
4                      Batman   acción            5
..                        ...      ...          ...
58                Toy Story 2  comedia            2
59                Toy Story 3  comedia            2
60                         Up  comedia            1
61              V de Vendetta   acción            1
62                      X-Men   acción            2

[63 rows x 3 columns]

In [15]:
#Media por nominación por cada género
df.groupby("genre")["nominations"].mean()

genre
acción     2.466667
comedia    2.052632
drama      2.894737
terror     1.600000
Name: nominations, dtype: float64

In [16]:
#ratio de nominación por cada película.
df["ratio_nominations"] = df.groupby("genre")["nominations"].transform(lambda x: x/x.mean())
df

                        title    genre  nominations  ratio_nominations
0   Abierto hasta el amanecer   terror            1           0.625000
1             American Beauty  comedia            4           1.948718
2             American Beauty    drama            4           1.381818
3             American Psycho   terror            2           1.250000
4                      Batman   acción            5           2.027027
..                        ...      ...          ...                ...
58                Toy Story 2  comedia            2           0.974359
59                Toy Story 3  comedia            2           0.974359
60                         Up  comedia            1           0.487179
61              V de Vendetta   acción            1           0.405405
62                      X-Men   acción            2           0.810811

[63 rows x 4 columns]

In [17]:
df.nlargest(3, columns="ratio_nominations")

                  title    genre  nominations  ratio_nominations
38   Mejor... imposible  comedia            5           2.435897
11  El caballero oscuro   acción            6           2.432432
12  El caballero oscuro    drama            6           2.072727

In [27]:
movies[movies['title']=='Mejor... imposible']

                   title  year    genre              name
222   Mejor... imposible  1997  comedia    Jack Nicholson
223   Mejor... imposible  1997  comedia
224   Mejor... imposible  1997  comedia        Helen Hunt
225   Mejor... imposible  1997  comedia
226   Mejor... imposible  1997  comedia      Greg Kinnear
227   Mejor... imposible  1997  comedia
228   Mejor... imposible  1997  comedia  Cuba Gooding Jr.
229   Mejor... imposible  1997  comedia
230   Mejor... imposible  1997  comedia      Skeet Ulrich
231   Mejor... imposible  1997  comedia
232   Mejor... imposible  1997  comedia    Shirley Knight
233   Mejor... imposible  1997  comedia
234   Mejor... imposible  1997  comedia       Jesse James
235   Mejor... imposible  1997  comedia
236   Mejor... imposible  1997  comedia   Lawrence Kasdan
1201  Mejor... imposible  1997    drama    Jack Nicholson
1202  Mejor... imposible  1997    drama
1203  Mejor... imposible  1997    drama        Helen Hunt
1204  Mejor... imposible  1997    drama
1205  Mejor... imposible  1997    drama      Greg Kinnear
1206  Mejor... imposible  1997    drama
1207  Mejor... imposible  1997    drama  Cuba Gooding Jr.
1208  Mejor... imposible  1997    drama
1209  Mejor... imposible  1997    drama      Skeet Ulrich
1210  Mejor... imposible  1997    drama
1211  Mejor... imposible  1997    drama    Shirley Knight
1212  Mejor... imposible  1997    drama
1213  Mejor... imposible  1997    drama       Jesse James
1214  Mejor... imposible  1997    drama
1215  Mejor... imposible  1997    drama   Lawrence Kasdan

## Película con mayor diferencia porcentual respecto a la media de su género es Mejor... Imposible (1997) protagonizada por Jack Nocholson.

In [18]:
df.nsmallest(3, columns="ratio_nominations")

                    title  genre  nominations  ratio_nominations
17            El pianista  drama            1           0.345455
32  La lista de Schindler  drama            1           0.345455
34       La vida es bella  drama            1           0.345455

## Películas con menores porcentuales respecto a la media de su género es El Pianista, La lista de Schindler y La vida es bella.