# Data processing.

In [1]:
import pandas as pd

In [2]:
# Specify the relative path to the CSV file
movies_path = '../results/movies.csv'

# Read the CSV file into a DataFrame
movies = pd.read_csv(movies_path)

# Display the DataFrame
print(movies.head())

                                               title  year   genre  \
0                                         The Matrix  1999  action
1  The Lord of the Rings: The Fellowship of the Ring  2001  action
2                                          Gladiator  2000  action
3                                Kill Bill: Volume 1  2003  action
4      The Lord of the Rings: The Return of the King  2003  action

                                              actors
0  Keanu Reeves,, Laurence Fishburne,, Carrie-Ann...
1  Elijah Wood,, Ian McKellen,, Viggo Mortensen,,...
2  Russell Crowe,, Joaquin Phoenix,, Connie Niels...
3  Uma Thurman,, Lucy Liu,, Daryl Hannah,, Vivica...
4  Elijah Wood,, Viggo Mortensen,, Ian McKellen,,...

In [3]:
movies["name"] = movies["actors"].str.split(",")
movies

,title,year,genre,actors,name
0,The Matrix,1999,action,"Keanu Reeves,, Laurence Fishburne,, Carrie-Ann...","[Keanu Reeves, , Laurence Fishburne, , Carri..."
1,The Lord of the Rings: The Fellowship of the Ring,2001,action,"Elijah Wood,, Ian McKellen,, Viggo Mortensen,,...","[Elijah Wood, , Ian McKellen, , Viggo Morten..."
2,Gladiator,2000,action,"Russell Crowe,, Joaquin Phoenix,, Connie Niels...","[Russell Crowe, , Joaquin Phoenix, , Connie ..."
3,Kill Bill: Volume 1,2003,action,"Uma Thurman,, Lucy Liu,, Daryl Hannah,, Vivica...","[Uma Thurman, , Lucy Liu, , Daryl Hannah, , ..."
4,The Lord of the Rings: The Return of the King,2003,action,"Elijah Wood,, Viggo Mortensen,, Ian McKellen,,...","[Elijah Wood, , Viggo Mortensen, , Ian McKel..."
...,...,...,...,...,...
115,Zombieland,2009,horror,"Jesse Eisenberg,, Woody Harrelson,, Emma Stone...","[Jesse Eisenberg, , Woody Harrelson, , Emma ..."
116,American Psycho,2000,horror,"Christian Bale,, Willem Dafoe,, Jared Leto,, J...","[Christian Bale, , Willem Dafoe, , Jared Let..."
117,From Dusk Till Dawn,1996,horror,"George Clooney,, Harvey Keitel,, Juliette Lewi...","[George Clooney, , Harvey Keitel, , Juliette..."
118,Final Destination,2000,horror,"Devon Sawa,, Ali Larter,, Kerr Smith,, Seann W...","[Devon Sawa, , Ali Larter, , Kerr Smith, , ..."
119,Let the Right One In,2008,horror,"Kåre Hedebrant,, Lina Leandersson,, Per Ragnar...","[Kåre Hedebrant, , Lina Leandersson, , Per R..."

In [4]:
movies = movies.explode("name").drop(columns="actors")
movies["name"] = movies["name"].str.strip()

In [5]:
movies = movies.reset_index(drop=True)

movies

                     title  year   genre                name
0               The Matrix  1999  action        Keanu Reeves
1               The Matrix  1999  action
2               The Matrix  1999  action  Laurence Fishburne
3               The Matrix  1999  action
4               The Matrix  1999  action    Carrie-Anne Moss
...                    ...   ...     ...                 ...
1049  Let the Right One In  2008  horror          Per Ragnar
1050  Let the Right One In  2008  horror
1051  Let the Right One In  2008  horror         Henrik Dahl
1052  Let the Right One In  2008  horror
1053  Let the Right One In  2008  horror     Karin Bergquist

[1054 rows x 4 columns]

In [7]:
movies.to_csv('movies_df.csv')