# Analysing the data.

## Genre with the most nominations:

In [1]:
import pandas as pd

In [2]:
movies_oscars = pd.read_csv('../results/movies_oscars.csv')

In [3]:
movies_oscars.groupby("genre")["nominations"].sum().sort_values(ascending=False)

genre
drama     52
action    32
comedy    32
horror    21
Name: nominations, dtype: int64

## The genre with the most nominations is drama.

In [4]:
movies_oscars = movies_oscars.groupby(["title", "genre"])["nominations"].sum()

In [5]:
movies_oscars = movies_oscars.reset_index()
movies_oscars

                                                title   genre  nominations
0                                       28 Days Later  horror            1
1                                     American Beauty  comedy            3
2                                     American Beauty   drama            3
3                                     American Psycho  horror            2
4                                  As Good As It Gets  comedy            5
5                                  As Good As It Gets   drama            5
6                                              Batman  action            4
7                                       Batman Begins  action            4
8                                            Big Fish   drama            2
9                               Bram Stoker's Dracula  horror            3
10                                         Fight Club   drama            2
11                                       Forrest Gump  comedy            4
12                                       Forrest Gump   drama            4
13                                From Dusk Till Dawn  horror            1
14                                          Gladiator  action            2
15                                          Gladiator   drama            2
16                                         Home Alone  comedy            1
17                                        I Am Legend  horror            1
18                                          Inception  action            2
19                 Indiana Jones and the Last Crusade  action            1
20               Indiana Jones and the Temple of Doom  action            1
21                               Inglourious Basterds  action            3
22                               Inglourious Basterds  comedy            3
23                         Interview With the Vampire  horror            1
24                                  Life Is Beautiful  comedy            1
25                                  Life Is Beautiful   drama            1
26                                 Men in Black (MIB)  action            2
27                                 Men in Black (MIB)  comedy            2
28                                Million Dollar Baby   drama            3
29                                       Moulin Rouge   drama            2
30                                       Mystic River   drama            4
31  Pirates of the Caribbean: The Curse of the Bla...  action            1
32  Pirates of the Caribbean: The Curse of the Bla...  comedy            1
33                                       Pretty Woman  comedy            1
34                                Requiem for a Dream   drama            3
35                                   Schindler's List   drama            1
36                                             Snatch  comedy            1
37                                   The Big Lebowski  comedy            2
38                The Curious Case of Benjamin Button   drama            4
39                                    The Dark Knight  action            5
40                                    The Dark Knight   drama            5
41                                       The Departed  action            4
42                                       The Departed   drama            4
43                                      The Lion King  comedy            1
44                                      The Lion King   drama            1
45                                         The Others  horror            1
46                                        The Pianist   drama            1
47                           The Shawshank Redemption   drama            2
48                                        The Shining  horror            3
49                           The Silence of the Lambs  horror            4
50                                            Titanic   drama            3
51                                          Toy Story  comedy            2
52                                        Toy Story 2  comedy            2
53                                        Toy Story 3  comedy            2
54                                                 Up  comedy            1
55                                     V for Vendetta  action            1
56                                  War of the Worlds  horror            1
57                                        World War Z  horror            1
58                                              X-Men  action            2
59                                         Zombieland  horror            2

## Mean of nominations by genre.

In [6]:
movies_oscars.groupby("genre")["nominations"].mean()

genre
action    2.461538
comedy    2.000000
drama     2.736842
horror    1.750000
Name: nominations, dtype: float64

## Nomination ratio by movie.

In [7]:
movies_oscars["ratio_nominations"] = movies_oscars.groupby("genre")["nominations"].transform(lambda x: x/x.mean())
movies_oscars

,title,genre,nominations,ratio_nominations
0,28 Days Later,horror,1,0.571429
1,American Beauty,comedy,3,1.500000
2,American Beauty,drama,3,1.096154
3,American Psycho,horror,2,1.142857
4,As Good As It Gets,comedy,5,2.500000
5,As Good As It Gets,drama,5,1.826923
6,Batman,action,4,1.625000
7,Batman Begins,action,4,1.625000
8,Big Fish,drama,2,0.730769
9,Bram Stoker's Dracula,horror,3,1.714286
10,Fight Club,drama,2,0.730769
11,Forrest Gump,comedy,4,2.000000
12,Forrest Gump,drama,4,1.461538
13,From Dusk Till Dawn,horror,1,0.571429
14,Gladiator,action,2,0.812500
15,Gladiator,drama,2,0.730769
16,Home Alone,comedy,1,0.500000
17,I Am Legend,horror,1,0.571429
18,Inception,action,2,0.812500
19,Indiana Jones and the Last Crusade,action,1,0.406250
20,Indiana Jones and the Temple of Doom,action,1,0.406250
21,Inglourious Basterds,action,3,1.218750
22,Inglourious Basterds,comedy,3,1.500000
23,Interview With the Vampire,horror,1,0.571429
24,Life Is Beautiful,comedy,1,0.500000
25,Life Is Beautiful,drama,1,0.365385
26,Men in Black (MIB),action,2,0.812500
27,Men in Black (MIB),comedy,2,1.000000
28,Million Dollar Baby,drama,3,1.096154
29,Moulin Rouge,drama,2,0.730769
30,Mystic River,drama,4,1.461538
31,Pirates of the Caribbean: The Curse of the Bla...,action,1,0.406250
32,Pirates of the Caribbean: The Curse of the Bla...,comedy,1,0.500000
33,Pretty Woman,comedy,1,0.500000
34,Requiem for a Dream,drama,3,1.096154
35,Schindler's List,drama,1,0.365385
36,Snatch,comedy,1,0.500000
37,The Big Lebowski,comedy,2,1.000000
38,The Curious Case of Benjamin Button,drama,4,1.461538
39,The Dark Knight,action,5,2.031250
40,The Dark Knight,drama,5,1.826923
41,The Departed,action,4,1.625000
42,The Departed,drama,4,1.461538
43,The Lion King,comedy,1,0.500000
44,The Lion King,drama,1,0.365385
45,The Others,horror,1,0.571429
46,The Pianist,drama,1,0.365385
47,The Shawshank Redemption,drama,2,0.730769
48,The Shining,horror,3,1.714286
49,The Silence of the Lambs,horror,4,2.285714
50,Titanic,drama,3,1.096154
51,Toy Story,comedy,2,1.000000
52,Toy Story 2,comedy,2,1.000000
53,Toy Story 3,comedy,2,1.000000
54,Up,comedy,1,0.500000
55,V for Vendetta,action,1,0.406250
56,War of the Worlds,horror,1,0.571429
57,World War Z,horror,1,0.571429
58,X-Men,action,2,0.812500
59,Zombieland,horror,2,1.142857

### Ratio by nominations.

In [8]:
movies_oscars.nlargest(3, columns="ratio_nominations")

                       title   genre  nominations  ratio_nominations
4         As Good As It Gets  comedy            5           2.500000
49  The Silence of the Lambs  horror            4           2.285714
39           The Dark Knight  action            5           2.031250

In [9]:
movies = pd.read_csv('../results/movies.csv')

In [10]:
movies[movies['title']=='As Good As It Gets']

,title,year,genre,actors
46,As Good As It Gets,1997,comedy,"Jack Nicholson,, Helen Hunt,, Greg Kinnear,, C..."
82,As Good As It Gets,1997,drama,"Jack Nicholson,, Helen Hunt,, Greg Kinnear,, C..."

### Movie with the greatest percentage difference compared to the average for its genre is As Good as it Gets (1997).

In [11]:
movies_oscars.nsmallest(3, columns="ratio_nominations")

                title  genre  nominations  ratio_nominations
25  Life Is Beautiful  drama            1           0.365385
35   Schindler's List  drama            1           0.365385
44      The Lion King  drama            1           0.365385